[tool.poetry]
name = "juniors-interview"
version = "0.1.0"
description = ""
authors = ["Anton <1566anton@gmail.com>"]
readme = "README.md"
packages = [{include = "juniors_interview"}]

[tool.poetry.dependencies]
python = "^3.11"
selenium = "^4.12.0"
webdriver-manager = "^4.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
