head_url = "https://ru.wikipedia.org"
main_url = head_url + "/wiki/Категория:Животные_по_алфавиту"
_animals_page_url = head_url + "/w/index.php?title=Категория%3AЖивотные_по_алфавиту"
letter_url = _animals_page_url + "&from={}"
list_from_url = _animals_page_url + "&filefrom={letter_1}&pagefrom={animal}&subcatfrom={letter_2}#mw-pages"
